GET http://localhost:8080/api/players/v1/

###

POST http://localhost:8080/api/players/v1
Content-Type: application/json

{
  "name": "Petar Sabo",
  "position": "CB",
  "team": "Manchester United",
  "nationalTeam": "Serbia",
  "dob": "1997-08-01"
}

###

PUT http://localhost:8080/api/players/v1/8
Content-Type: application/json

{
  "name": "Marko Jankovic",
  "position": "ST",
  "team": "Manchester City",
  "nationalTeam": "Serbia",
  "dob": "1997-08-01",
  "version": 0
}

###

DELETE http://localhost:8080/api/players/v1/3
}