GET http://localhost:8080/api/players/v1/

###

POST http://localhost:8080/api/player/v1
Content-Type: application/json

{
  "name": "Petar Sabo",
  "position": "CB",
  "team": "Manchester United",
  "nationalTeam": "Serbia",
  "dob": "1997-08-01"
}

###

PUT http://localhost:8080/api/player/v1/4
Content-Type: application/json

{
  "name": "Petar Sucic",
  "position": "CB",
  "team": "Manchester United",
  "nationalTeam": "Serbia",
  "dob": "1997-08-01"
}

###

DELETE http://localhost:8080/api/player/v1/3
}